[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Keiran Jensen <keiranjensen@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
